#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -d "$OPENSHIFT_DATA_DIR/content/data" ]; then
        mkdir -p $OPENSHIFT_DATA_DIR/content/data
fi

if [ ! -d "$OPENSHIFT_DATA_DIR/content/images" ]; then
        mkdir -p $OPENSHIFT_DATA_DIR/content/images
fi

ln -sf $OPENSHIFT_DATA_DIR/content/data $OPENSHIFT_REPO_DIR/content/data
ln -sf $OPENSHIFT_DATA_DIR/content/images $OPENSHIFT_REPO_DIR/content/images

set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "CREATE table $OPENSHIFT_APP_NAME;" > /dev/null 2>&1
then
    echo
    echo "Database schema not found, importing 'phpbb.sql' schema."
    echo
    cat "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/phpbb.sql" |sed -e s/"phpbb-dbvs.rhcloud.com"/"$OPENSHIFT_APP_DNS"/g -e s/\`phpbb\`/\`$OPENSHIFT_APP_NAME\`/ > "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/phpbb2.sql" 
    /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" --verbose $OPENSHIFT_APP_NAME < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/phpbb2.sql"
    echo
    echo "done."
    echo "=================================================="
    echo "  phpbb admin login: admin"
    echo "  phpbb admin password: OpenShiftAdmin"
    echo "  Don't forget to change your phpbb admin password!"
    echo "=================================================="
else
    echo "Database found, skipping import."
fi
